# Generated by Django 5.0.4 on 2024-05-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='specialists_images/')),
            ],
        ),
    ]
