# Generated by Django 5.0.4 on 2024-05-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='title',
        ),
        migrations.AddField(
            model_name='specialist',
            name='tags',
            field=models.ManyToManyField(related_name='specialists', to='main.tag'),
        ),
    ]
