# Generated by Django 5.0.4 on 2024-05-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tag_remove_specialist_title_specialist_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SessionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_range', models.CharField(choices=[('<1000', 'Менше 1000 грн'), ('1000-2000', '1000 - 2000 грн'), ('>2000', 'Більше 2000 грн')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialistGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Чоловік'), ('female', 'Жінка')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TherapyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('personal', 'Особиста'), ('couple', 'Парна'), ('child', 'Дитяча')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='specialist',
            name='experience',
            field=models.ManyToManyField(blank=True, to='main.experience'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='method',
            field=models.ManyToManyField(blank=True, to='main.method'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='preference',
            field=models.ManyToManyField(blank=True, to='main.preference'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='price',
            field=models.ManyToManyField(blank=True, to='main.sessionprice'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='gender',
            field=models.ManyToManyField(blank=True, to='main.specialistgender'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='therapy_type',
            field=models.ManyToManyField(blank=True, to='main.therapytype'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='topic',
            field=models.ManyToManyField(blank=True, to='main.topic'),
        ),
    ]
