# Generated by Django 5.0.4 on 2024-05-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_experience_method_preference_sessionprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='method',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='preference',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='price',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='therapy_type',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Method',
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
        migrations.DeleteModel(
            name='SessionPrice',
        ),
        migrations.DeleteModel(
            name='SpecialistGender',
        ),
        migrations.DeleteModel(
            name='TherapyType',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
