# Generated by Django 5.0.4 on 2024-05-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_specialist_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='about_me',
            field=models.TextField(default='temporary default', verbose_name='Про мене'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialist',
            name='education',
            field=models.TextField(default='temporary default', verbose_name='Освіта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialist',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Ціна послуг'),
            preserve_default=False,
        ),
    ]
