# Generated by Django 5.0.4 on 2024-05-03 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_certification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialist',
            old_name='reviews',
            new_name='review_count',
        ),
        migrations.AlterField(
            model_name='specialist',
            name='about_me',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='education',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='service_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('text', models.TextField()),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.specialist')),
            ],
        ),
    ]
