# Generated by Django 5.0.4 on 2024-05-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_tag_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
    ]
